---
kind: pipeline
name: testing
type: vm

platform:
  os: linux
  arch: amd64
pool:
  use: ubuntu

steps:
  - name: vet
    pull: always
    image: golang:1.19
    commands:
      - go vet ./...
    environment:
      GO111MODULE: on
    volumes:
      - name: gopath
        path: /go

  - name: test
    pull: always
    image: golang:1.19
    commands:
      - go test -cover ./...
    environment:
      GO111MODULE: on
    volumes:
      - name: gopath
        path: /go

volumes:
  - name: gopath
    temp: {}

trigger:
  ref:
    - refs/heads/master
    - "refs/tags/**"
    - "refs/pull/**"

---
kind: pipeline
name: linux-amd64
type: vm

platform:
  os: linux
  arch: amd64
pool:
  use: ubuntu

steps:
  - name: build-push
    pull: always
    image: golang:1.19
    commands:
      - 'go build -v -ldflags "-X main.version=${DRONE_COMMIT_SHA:0:8}" -a -tags netgo -o release/linux/amd64/drone-slack-blame'
    environment:
      CGO_ENABLED: 0
      GO111MODULE: on
    when:
      event:
        exclude:
          - tag

  - name: build-tag
    pull: always
    image: golang:1.19
    commands:
      - 'go build -v -ldflags "-X main.version=${DRONE_TAG##v}" -a -tags netgo -o release/linux/amd64/drone-slack-blame'
    environment:
      CGO_ENABLED: 0
      GO111MODULE: on
    when:
      event:
        - tag

  - name: executable
    pull: always
    image: golang:1.19
    commands:
      - ./release/linux/amd64/drone-slack-blame --help

  - name: publish
    pull: always
    image: plugins/docker:linux-amd64
    settings:
      auto_tag: true
      auto_tag_suffix: linux-amd64
      daemon_off: false
      dockerfile: docker/Dockerfile.linux.amd64
      password:
        from_secret: docker_password
      repo: plugins/slack-blame
      username:
        from_secret: docker_username
    when:
      ref:
        - refs/heads/master
        - refs/tags/**

trigger:
  ref:
    - refs/heads/master
    - "refs/tags/**"
    - "refs/pull/**"

depends_on:
  - testing

---
kind: pipeline
name: linux-arm64
type: vm

platform:
  os: linux
  arch: arm64
pool:
  use: ubuntu_arm64

steps:
  - name: build-push
    pull: always
    image: golang:1.19
    commands:
      - 'go build -v -ldflags "-X main.version=${DRONE_COMMIT_SHA:0:8}" -a -tags netgo -o release/linux/arm64/drone-slack-blame'
    environment:
      CGO_ENABLED: 0
      GO111MODULE: on
    when:
      event:
        exclude:
          - tag

  - name: build-tag
    pull: always
    image: golang:1.19
    commands:
      - 'go build -v -ldflags "-X main.version=${DRONE_TAG##v}" -a -tags netgo -o release/linux/arm64/drone-slack-blame'
    environment:
      CGO_ENABLED: 0
      GO111MODULE: on
    when:
      event:
        - tag

  - name: executable
    pull: always
    image: golang:1.19
    commands:
      - ./release/linux/arm64/drone-slack-blame --help

  - name: publish
    pull: always
    image: plugins/docker:linux-arm64
    settings:
      auto_tag: true
      auto_tag_suffix: linux-arm64
      daemon_off: false
      dockerfile: docker/Dockerfile.linux.arm64
      password:
        from_secret: docker_password
      repo: plugins/slack-blame
      username:
        from_secret: docker_username
    when:
      ref:
        - refs/heads/master
        - refs/tags/**

trigger:
  ref:
    - refs/heads/master
    - "refs/tags/**"
    - "refs/pull/**"

depends_on:
  - testing

---
kind: pipeline
type: vm
name: windows-1809

platform:
  os: windows
  arch: amd64

pool:
  use: windows

steps:
  - name: environment
    image: golang:1.19
    pull: always
    environment:
      CGO_ENABLED: "0"
    commands:
      - go version
      - go env
  - name: build
    image: golang:1.19
    environment:
      CGO_ENABLED: "0"
    commands:
      - go build -v -ldflags "-X main.version=" -a -tags netgo -o release/windows/amd64/drone-slack-blame.exe .
  - name: docker
    image: plugins/docker
    settings:
      dockerfile: docker/Dockerfile.windows.1809
      repo: plugins/slack-blame
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      auto_tag: true
      auto_tag_suffix: windows-1809-amd64
      daemon_off: true
      purge: false
    when:
      ref:
        - refs/heads/master
        - refs/tags/**
depends_on:
  - testing
trigger:
  ref:
    - refs/heads/master
    - refs/tags/**
    - refs/pull/**

---
kind: pipeline
type: vm
name: windows-ltsc2022

platform:
  os: windows
  arch: amd64

pool:
  use: windows-2022

steps:
  - name: environment
    image: golang:1.19
    pull: always
    environment:
      CGO_ENABLED: "0"
    commands:
      - go version
      - go env
  - name: build
    image: golang:1.19
    environment:
      CGO_ENABLED: "0"
    commands:
      - go build -v -ldflags "-X main.version=" -a -tags netgo -o release/windows/amd64/drone-slack-blame.exe .
  - name: docker
    image: plugins/docker
    settings:
      dockerfile: docker/Dockerfile.windows.ltsc2022
      repo: plugins/slack-blame
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      auto_tag: true
      auto_tag_suffix: windows-ltsc2022-amd64
      daemon_off: true
      purge: false
    when:
      ref:
        - refs/heads/master
        - refs/tags/**
depends_on:
  - testing
trigger:
  ref:
    - refs/heads/master
    - refs/tags/**
    - refs/pull/**

---
kind: pipeline
name: notifications
type: vm

platform:
  os: linux
  arch: amd64
pool:
  use: ubuntu

steps:
  - name: manifest
    pull: always
    image: plugins/manifest
    settings:
      auto_tag: true
      ignore_missing: true
      password:
        from_secret: docker_password
      spec: docker/manifest.tmpl
      username:
        from_secret: docker_username

trigger:
  ref:
    - refs/heads/master
    - "refs/tags/**"

depends_on:
  - linux-amd64
  - linux-arm64
  - windows-1809
  - windows-ltsc2022
